version: '3.4'

services:
  postgres:
    image: postgres:12.0-alpine
    container_name: scone_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=superscone
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 15432:5432

  redis:
    image: redis:3.2
    container_name: scone_redis
    ports:
      - 6379:6379

volumes:
  postgres_data:
