# Generated by Django 3.1.1 on 2020-09-23 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=1024, null=True)),
                ('extension', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('uri', models.CharField(blank=True, max_length=2048, null=True, unique=True)),
                ('image', models.ImageField(upload_to='crop/picture/image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
