# Generated by Django 3.1.1 on 2020-09-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='height',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='width',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(null=True, upload_to='crop/crop/image'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to='crop/picture/image'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='uri',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True, unique=True),
        ),
    ]
